name: avatar_better
description: "This is a complete avatar package that you can use for your profile and avatar."
version: 0.1.1
homepage: https://github.com/SwanFlutter/avatar_better.git
uses-material-design: This

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:



environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  zoom_hover_pinch_image: ^1.0.4
  image_cropping: ^0.0.15
  flutter_saver: ^0.0.5
  permission_master: ^0.0.5
  path_provider: ^2.0.0
  device_info_plus: ^11.4.0
    




dev_dependencies:
  
  flutter_lints: ^5.0.0


flutter:


